### PR TITLE
Change Capacity of Ender Tank

### PR DESCRIPTION
**Pull request by alphaNOVAircraft**
Ref: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7144

### CODE REVIEW

**Comment by Ethryan** [comment]
4096 buckets looks a bit extreme

**Comment by alphaNOVAircraft** [comment]
Its the same as a super tank 1, which is extremly cheaper, the capacity isnt the real deal here, noone will use it just fpr storage. It must be that high to be no bottleneck even with UEV pumps, which seems fine for me. Suggest another number?!

**Review by Ethryan — COMMENTED** [review]
"Snip"

i would much rather that a new tier of tank is added, instead of editing the capacity of the original one.

**Comment by alphaNOVAircraft** [comment]
I am currently trying to add a second tier of ender tank. But im completly new to modding, i hope i get it to work but i cant really promise anything.

**Comment by Dream-Master** [comment]
but this change we can add now i guess. Feel free to make a new pr for add a new tiered tank

**Review by Dream-Master — APPROVED** [review]

**Comment by mitchej123** [comment]
Original one worked fine for vanilla, or less demanding modpacks and it being available earlier.  This is available at IV; bumping it up makes perfect sense to me.

**Pull request merged**
